name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      # - uses: actions/setup-go@v2
      #   with:
      #     go-version: '^1.13.1'

      - name: Install development.txt
        run: |
          python3 -m pip install -r development.txt

      - name: Install cibuildwheel
        run: |
          python3 -m pip install cibuildwheel==1.6.4

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y

      - name: Build wheels
        env:
          CIBW_SKIP: cp27-*
        run: |
          python3 -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl